# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7fb0a6735de8da4766f16d025b58ce5cb249563b6c4d1ebe32b715831618c1387960c232ec1f04f7a0c1d073dfef4af879d2ae75cf70c617b1a8321cbc83d1

test:
  secret_key_base: d14d804f7a4158db99f6a10e61b4be46da1eb01ca29158cb53716baf0f9c9a8e4256ea2a7c64b247c95d1fc3d752e76397d344c58a58c5fcaa004b97856b1e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
